"""Synthetic RSX metadata, including conflicts and partial exports."""
import json
from pathlib import Path
import tempfile
import unittest

from apex_tex.animation_names import NameCatalog, bundled_catalog, read_settings, string_guid, iter_localization


class AnimationNamesTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.locl = self.root / 'localization' / 'test.locl'
        self.locl.parent.mkdir()
        self.items = self.root / 'settings' / 'itemflav' / 'character_emote' / 'test_legend'
        self.items.mkdir(parents=True)

    def language(self, values):
        self.locl.write_text('"localization_test"\n{\n' + ''.join(
            '"%x" %s\n' % (string_guid(key), json.dumps(value, ensure_ascii=False))
            for key, value in values.items()) + '}\n', encoding='utf-8')

    def item(self, filename='test.json', **overrides):
        settings = dict(itemType='character_emote', localizationKey_NAME='#TEST_NAME',
                        anim3p='test_emote', anim3pLoop='test_emote_loop')
        settings.update(overrides)
        (self.items / filename).write_text(json.dumps({'settings': settings}), encoding='utf-8')

    def scan(self):
        catalog = NameCatalog()
        list(catalog.read(self.locl))
        return catalog

    def test_guid_known_external_vectors_and_normalization(self):
        # Fixed vectors from RSX's public Localization.md and asset list;
        # expectations are not generated by this implementation.
        self.assertEqual(string_guid('spray_heart_01'), 0xfff4877635538a03)
        self.assertEqual(string_guid('settings/scriptAnimWindow/fx_wraithhandmenu_sm.rpak'), 0x29fe2cdb09285aa2)
        self.assertEqual(string_guid('SETTINGS\\SCRIPTANIMWINDOW\\FX_WRAITHHANDMENU_SM.RPAK'), 0x29fe2cdb09285aa2)

    def test_names_unicode_escapes_and_loop_roles(self):
        self.language({'TEST_NAME': 'Étoile "bleue" \\ Test'})
        self.item()
        catalog = self.scan()
        self.assertEqual(catalog.match(0, string_guid('test_emote')), ('Étoile "bleue" \\ Test', '', False))
        self.assertEqual(catalog.match(0, string_guid('test_emote_loop'))[1], 'Loop')
        self.assertEqual(catalog.match(0, string_guid('test_emote_other')), ('', '', False))

    def test_full_guid_and_short_hash_have_separate_namespaces(self):
        self.language({'TEST_NAME': 'Sample Pose'})
        ref = 'animseq/humans/test/test_pose.rseq'
        self.item(itemType='gladiator_card_stance', stillAnimSeq=ref, lightingRigStillAnimSeq='lights')
        catalog = self.scan()
        self.assertEqual(catalog.match(string_guid(ref), 0), ('Sample Pose', 'Still', False))
        self.assertEqual(catalog.match(0, string_guid(ref)), ('', '', False))
        self.assertEqual(catalog.match(string_guid('lights'), 0), ('', '', False))

    def test_different_items_sharing_animation_are_not_guessed(self):
        self.language({'TEST_NAME': 'First Name', 'OTHER': 'Second Name'})
        self.item()
        self.item('second.json', localizationKey_NAME='#OTHER')
        self.assertEqual(self.scan().match(0, string_guid('test_emote')), ('', '', True))

    def test_missing_translation_can_make_a_match_ambiguous(self):
        self.language({'TEST_NAME': 'First Name'})
        self.item()
        self.item('missing.json', localizationKey_NAME='#NOT_EXPORTED')
        self.assertEqual(self.scan().match(0, string_guid('test_emote')), ('', '', True))

    def test_identical_references_and_names_are_not_ambiguous(self):
        self.language({'TEST_NAME': 'First Name'})
        self.item()
        self.item('duplicate.json')
        self.assertEqual(self.scan().match(0, string_guid('test_emote')), ('First Name', '', False))

    def test_wrong_settings_location_is_actionable(self):
        self.language({'TEST_NAME': 'Example'})
        self.items.rmdir()
        self.items.parent.rmdir()
        with self.assertRaisesRegex(ValueError, 'settings were not found'):
            self.scan()

    def test_truncated_and_conflicting_localization_fail(self):
        for body in ('"test"\n{\n"a" "one"\n', '"test"\n{\n"a" "one"\n"a" "two"\n}\n'):
            self.locl.write_text(body, encoding='utf-8')
            with self.assertRaises(ValueError):
                list(iter_localization(self.locl, {}))

    def test_bad_item_json_fails_instead_of_partial_name_map(self):
        self.language({'TEST_NAME': 'Example'})
        self.item()
        (self.items / 'broken.json').write_text('{', encoding='utf-8')
        with self.assertRaises(ValueError):
            self.scan()

    def test_settings_override_and_cancel_release_files(self):
        self.language({'TEST_NAME': 'Example'})
        self.item()
        catalog = NameCatalog()
        steps = catalog.read(self.locl, str(self.root / 'settings'))
        next(steps)
        steps.close()
        (self.items / 'test.json').unlink()
        self.locl.unlink()

    def test_rsx_mod_comments_preserve_quoted_slashes(self):
        path = self.items / 'modded.json'
        path.write_text('''{
          "settings": {"itemType": "character_emote", "description": "https://example.test//value"},
          "$modValues": [{ // originally mapped to offset 184
            "index": 0, "type": "string", "value": "", "field": "anim3pLoop"
          }]
        }''', encoding='utf-8')
        settings = read_settings(path)
        self.assertEqual(settings['description'], 'https://example.test//value')

    def test_catalogue_roundtrip_retains_conflicts_across_namespaces(self):
        original = NameCatalog()
        original.full[1] = {('Name A', ''), ('Name B', '')}
        original.short[2] = {('Name A', '')}
        original.full[3] = {('Single Name', 'Still'), ('Single Name', 'Animated')}
        restored = NameCatalog.from_snapshot(original.snapshot(language='English'))
        self.assertEqual(restored.match(1, 2), ('', '', True))
        self.assertEqual(restored.match(3, 0), ('Single Name', '', False))

    def test_catalogue_validation(self):
        for value in (['Name', []], ['', ''], ['Name', 'Victim'], 'Name'):
            with self.assertRaises(ValueError):
                NameCatalog.from_snapshot({'schema': 1, 'full': {'01': value}, 'short': {}})
        with self.assertRaises(ValueError):
            NameCatalog.from_snapshot({'schema': 2, 'full': {}, 'short': {}})
        with self.assertRaises(ValueError):
            NameCatalog.from_snapshot({'schema': 1, 'full': {'not-a-guid': None}, 'short': {}})

    def test_included_catalogue_has_known_names_without_exports(self):
        catalog = bundled_catalog()
        self.assertEqual(catalog.match(0, string_guid('wraith_ground_emote_energy')), ('Acrobat', '', False))
        self.assertEqual(catalog.match(string_guid('animseq/humans/class/light/pilot_light_wraith/wraith_execution_blink.rseq'), 0),
                         ('Existential Crisis', '', False))
        self.assertEqual(catalog.match(0, 0), ('', '', False))
        self.assertGreater(len(catalog.full) + len(catalog.short), 1000)
        self.assertIs(catalog, bundled_catalog())


if __name__ == '__main__':
    unittest.main()
